# Generated by Django 5.0.4 on 2024-05-11 03:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welcome', '0003_teamname_teammember_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='welcome.teamname'),
        ),
    ]
